routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\LocaleSessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterProfessionController;
use App\Http\Controllers\ProfessionController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\ItemController;

use App\Http\Controllers\Auth\SessionController;

use App\Http\Controllers\Admin\UserController as AdminUserController;

require "oauth.php";

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CharacterController::class, 'index'])->name('home');

Route::name('auth.')->group(function () {
    Route::view('/login', 'auth.login')->name('login');
    Route::post('/login', [SessionController::class, 'store'])->name('login.store');
    Route::delete('/logout', [SessionController::class, 'destroy'])->name('logout');
});

//  Public section
// ----------------------------

Route::get('/lang/{locale}', [LocaleSessionController::class, 'store'])->name('locale.store');

Route::prefix('user')->name('user.')->group(function() {
    Route::get('{user}', [UserController::class, 'show'])->name('show');
});

Route::prefix('characters')->name('character.')->group(function() {
    Route::get('create', [CharacterController::class, 'create'])->name('create');
    Route::post('create', [CharacterController::class, 'store'])->name('store');

    // Character
    Route::prefix('{character}')->group(function () {

        // Character Professions
        Route::prefix('professions')->name('profession.')->group(function() {
            Route::get('/create', [CharacterProfessionController::class, 'create'])->name('create');
            Route::post('/', [CharacterProfessionController::class, 'store'])->name('store');
            Route::get('/{profession}', [CharacterProfessionController::class, 'show'])->name('show');
            Route::delete('/{profession}', [CharacterProfessionController::class, 'destroy'])->name('destroy');
        });

        Route::get('/', [CharacterController::class, 'show'])->name('show');
        Route::get('/edit', [CharacterController::class, 'edit'])->name('edit');
        Route::delete('/', [CharacterController::class, 'destroy'])->name('destroy');
    });
});

// Recipes
Route::prefix('recipes')->name('recipe.')->group(function () {
    Route::get('/', [RecipeController::class, 'index'])->name('index');
    Route::get('/{recipe}', [RecipeController::class, 'show'])->name('show');
});

// Items
Route::prefix('items')->name('item.')->group(function () {
    Route::get('/', [ItemController::class, 'index'])->name('index');
    Route::get('/{item}', [ItemController::class, 'show'])->name('show');
});

//  Authenticated section
// ----------------------------
Route::middleware(['auth'])->group(function() {

    // Profession
    Route::prefix('profession')->name('profession.')->group(function() {
        Route::get('/create', [ProfessionController::class, 'create'])->name('create');
        Route::post('/', [ProfessionController::class, 'store'])->name('store');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', [ProfileController::class, 'index'])->name('index');
        Route::get('/edit', [ProfileController::class, 'edit'])->name('edit');
        Route::post('/', [ProfileController::class, 'update'])->name('update');
    });

    // Admin
    Route::middleware(['can:administrate'])->prefix('admin')->name('admin.')->group(function () {

        Route::resource('users', AdminUserController::class)->except(['show', 'store', 'update']);
    });
});

app/View/Components/Layout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Layout extends Component
{
    /**
     * Layout script
     */
    protected string $name;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($name = 'default')
    {
        $this->name = $name;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view("layouts.{$this->name}");
    }
}

app/View/Components/WowheadScript.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

/**
 * Render wowhead tooltip javascript
 */
class WowheadScript extends Component
{
    public $options;

    /**
     * Option keys.
     */
    protected static $keys = [
        'iconSize',
        'colorLinks',
        'iconizeLinks',
        'renameLinks',
        'hide'
    ];

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        $this->options = collect(config('wowhead'))
            ->only(self::$keys)
            ->filter(function ($value, $key) {
                return is_array($value) ? count($value) : $value !== null;
            });

        return <<<'html'
        <script>const whTooltips=<?php echo json_encode($options) ?>;</script>
        <script src="https://wow.zamimg.com/widgets/power.js"></script>
        html;
    }
}

resources/views/layouts/app.blade.php
<x-layout class="bg-gray-200">

    @include('partials.navigation')

    <!-- Page title starts -->
    <div class="relative z-10 bg-gray-800 pt-8 pb-16">
        <div class="max-w-7xl px-6 mx-auto flex items-start justify-between">
            <div>
                <h4 class="text-2xl font-bold leading-tight text-white">
                    {{ $title }}
                </h4>
            </div>

            @if (isset($page_links))
            <div class="flex space-x-2">
                {{ $page_links }}
            </div>
            @endif
        </div>
    </div>
    <!-- Page title ends -->

    <!-- Main content -->
    <div class="mx-4">
        <main class="max-w-7xl min-h-16 mx-auto -mt-8 relative z-10 rounded shadow bg-white">

            <x-notifications />

            {{ $slot }}
        </main>
    </div>
    <!-- Main content ends -->

    @include('partials.footer')

</x-layout>

resources/views/layouts/auth.blade.php
<x-layout class="bg-gray-100">

    <div class="mx-auto max-w-sm mt-48 border rounded p-4 bg-white">

        <x-notifications />

        {{ $slot }}
    </div>

</x-layout>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @livewireStyles
</head>
<body {{ $attributes->merge(['class' => 'antialiased']) }}>

{{ $slot }}

<!-- Scripts -->
@livewireScripts
<x-wowhead-script />
<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/error.blade.php
<x-layout name="app">

<x-slot name="title">
    {{ __('Error') }} - {{ $title }}
</x-slot>

<div class="py-12 text-center text-gray-500">

    @if (isset($icon))
    <x-icon :name="$icon" class="h-24 w-24 mx-auto {{ $icon_color ?? 'text-red-500' }} mb-4" />
    @endif

    <h1 class="text-3xl mb-4">{{ $title }}</h1>
    <p>{{ $slot }}</p>
</div>

</x-layout>